# Setup
title:               The Exit Strategy
tagline:             'Additive Manufacturing, Optimization & Emergent Phenoemena'
description:         'Blank Page'
url:                 
baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Christoph Breuning
  url:               https://twitter.com/chrisbreu
  email:             

# Gems
plugins:
  - jekyll-paginate

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
